# .gitleaks.toml - Configuración de escaneo de seguridad para Token 10 Protocol

title = "Token 10 Protocol Security Config"
version = "1.0"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api_key|apikey|api-key|secret_key|secretkey|secret-key)[\s]*=[\s]*["'][^"']{10,50}["']'''
tags = ["key", "api"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9._-]*|eyJ[A-Za-z0-9_\/+-]*\.[A-Za-z0-9._\/+-]*'''
tags = ["jwt", "token"]

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----'''
tags = ["key", "private"]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}'''
tags = ["github", "token"]

[[rules]]
id = "password-in-code"
description = "Password in code"
regex = '''(password|passwd|pwd)[\s]*=[\s]*["'][^"']{4,}["']'''
tags = ["password", "hardcoded"]

# Excluir archivos legítimos que puedan contener patrones similares
[[allowlist]]
description = "Allow documentation files"
files = ['''.*\.md$''', '''.*\.txt$''']

[[allowlist]]
description = "Allow test files"
files = ['''.*test.*''', '''.*spec.*''', '''.*example.*''']

[[allowlist]]
description = "Allow config files in .github"
files = ['''.github/.*''']

[[allowlist]]
description = "Allow specific nucleo config files"
files = ['''nucleo/\.acceso/.*''']
